### PR TITLE
 Password peek 🫣 - take two 

### LINKED ISSUE #1254: Add option to see/peek at the password
## The problem

When you are using the passwort protection you can only see the dots. When you tipe your password like "testPW" maybe it's possible to write "restPW" or something else. It doesn't matter in short Passwort phrases but when you use a longer one with special symbols, it's not possible to check the password and maybe you can not open the message.
When I want to send a file to some people with the option to download the file a long time with PrivateBin and wrote a wrong  password, you can't open or download the file anymore.

## The solution

Adding an "eye-button" to show the password until click the "eye-button" again

## Alternatives

Adding these option to the config file to enable it just if you want to. So the user who doesn't want these feature (because of security or other reasons) it can be disabled.

### PR DESCRIPTION
**Pull request by elrido**
This PR closes #1254 & superseedes #1647.

## Changes
* Added password peek (by @karthikkasturi in #1647)
* Re-use existing bootstrap 3 glyphicons
* Added bootstrap 5 "eye" & "eye-slash" icons
* Extended logic to replace the two sets of icons

### CODE REVIEW

File: js/privatebin.js [hunk 1]
```diff
@@ -5675,6 +5675,73 @@ jQuery.PrivateBin = (function($) {
...
+         * @function
+         */
+        function handleRevealButtonClick() {
+            const element = $(this);
+            const passwordInput = element.siblings('.input-password');
+			const isHidden = passwordInput.attr('type') === 'password';
+
+            passwordInput.attr('type', isHidden ? 'text' : 'password');
+
+			const tooltip = I18n._(isHidden ? 'Hide password' : 'Show password as plain text. Warning: this will display your password on the screen.');
```
Comment (rugk) [inline js/privatebin.js]:
```suggestion
			const tooltip = I18n._(isHidden ? 'Hide password' : 'Show password');
```

IMHO this text would be enough, would not it?  I mean it's a common feature and what should "Show password" do otherwise?

**Review by rugk — APPROVED** [review]
Apart from that one little wording am unsure about, LGTM!

Also big credits go to @karthikkasturi I suppose.

File: js/privatebin.js (hunk 1 above)
Comment (elrido) [reply js/privatebin.js]: agreed, and applied in 23624d693c40d962fdf49c73611ee46c56acd2df - please review again and approve or merge if happy, thanks!

**Comment by karthikkasturi** [comment]
Thanks for the follow up work on this @elrido. I was going to work on it myself but i haven't had time the past couple of weeks. Sorry and thanks again!

**Comment by brunob** [comment]
Nice thing added, but it seems a bit broken with bootstrap template see https://0g.gg/ or https://bin.infini.fr/

**Comment by elrido** [comment]
> Nice thing added, but it seems a bit broken with bootstrap template see https://0g.gg/ or https://bin.infini.fr/

Should be resolved with b7286cf99ad1f5dc493e27f93a73b6ef192332f0 - missed the parent class for the [input group](https://getbootstrap.com/docs/3.4/css/#form-inline-with-input-group).
