### PR TITLE
ensure English is always added to available languages, fixes #1208

### LINKED ISSUE #1208: English language is not selectable since v1.6.1
**Did you use the FAQ section?**
- [x] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

## Steps to reproduce

1. Install PrivateBin v1.6.1
2. Try to change auto-detected language to English

### What happens

English is not one of selectable languages

### What should happen

User should always be able to switch to English, just like any other language

## Additional information

Caused by https://github.com/PrivateBin/PrivateBin/commit/896a49c8cf96ae9351796bd84050d2a0b249ddb3

## Basic information

**Server address**: N/A

**Server OS:** N/A

**Webserver:** N/A

**Browser:** N/A

**PrivateBin version:** v1.6.1

I can reproduce this issue on <https://privatebin.net>: Yes

### PR DESCRIPTION
**Pull request by elrido**
This PR fixes #1208

## Changes
* always add en to available languages
* use globs to fetch only the language files (2 and 3 letter .json files under i18n folder)
* don't add en twice

bug got introduced in 3668f1e3f4808d7232606349035c6a43c5a84c23 and started affecting release 1.6.1 after 896a49c8cf96ae9351796bd84050d2a0b249ddb3

### CODE REVIEW

**Comment by elrido** [comment]
@rugk or @r4sas - would you have time to review this till the weekend? I'd like to release 1.6.2 once this got merged.

**Review by rugk — APPROVED** [review]
Okay if you wanna do a fast patch release.

Only a generic thing: Is there a (regression) (unit) test catching the exact issue reported? I don't see one added or modified here, so well…

(Note of course best software dev practise would be test-driven-developmemnt, so writing the test for the bug first, seeing the error and only then fixing it hehe. This also makes sure the bug is and stays fixed, especially a suble one like this apparently was. And makes code more understandable.)

File: lib/I18n.php [hunk 1]
```diff
@@ -193,10 +196,14 @@ public static function loadTranslations()
...
-            while (false !== ($file = $i18n->read())) {
-                if (preg_match('/^([a-z]{2,3}).json$/', $file, $match) === 1) {
-                    self::$_availableLanguages[] = $match[1];
+            self::$_availableLanguages[] = 'en'; // en.json is not part of the release archive
+            $languageIterator            = new AppendIterator();
+            $languageIterator->append(new GlobIterator(self::_getPath('??.json')));
+            $languageIterator->append(new GlobIterator(self::_getPath('???.json'))); // for jbo
+            foreach ($languageIterator as $file) {
+                $language = $file->getBasename('.json');
+                if ($language != 'en') {
```
Comment (rugk) [inline lib/I18n.php:205]: This seems to ensure en does not end up two times. Okay likely has no bad effect, but yeah. IN a potential unit test that would be another test case.

As said, feel free to do tests, if you want, in another PR.

**Review by rugk — COMMENTED** [review]
BTW another remark: This is much more readable and much better code! (with these more modern PHP features/iterators) So good refactoring here! :tada:

File: lib/I18n.php (hunk 1 above)
Comment (elrido) [reply lib/I18n.php:205]: Correct, the issue is that in the git repo (and therefore during testing) the en.json file is present. It only got introduced for crowdin, as that requires a base translation file to copy for new languages, which is why we used to have logic that artificially added the "en" entry to the list. In the release the file is excluded via gitattributes, as it should not get read by anything (waste of a disk read and parsing CPU-cycles, as there is nothing to do).

Reg. test: Could copy all the translations into a temp dir, change PUBLIC_PATH to point to it, then do one call to getAvailableLanguages() with the file present and one when removed, comparing the two results. It is doable, if a little convoluted. I'll raise another PR later on.

Comment (rugk) [reply lib/I18n.php:205]: Yeah that test idea sounds fine (It's more an integration test, but that's okay, if mocking the dependencies [in this case the file system] is not possible).
