### PR TITLE
prevent regression around presence or absence of en.json

### LINKED ISSUE #1208: English language is not selectable since v1.6.1
**Did you use the FAQ section?**
- [x] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

## Steps to reproduce

1. Install PrivateBin v1.6.1
2. Try to change auto-detected language to English

### What happens

English is not one of selectable languages

### What should happen

User should always be able to switch to English, just like any other language

## Additional information

Caused by https://github.com/PrivateBin/PrivateBin/commit/896a49c8cf96ae9351796bd84050d2a0b249ddb3

## Basic information

**Server address**: N/A

**Server OS:** N/A

**Webserver:** N/A

**Browser:** N/A

**PrivateBin version:** v1.6.1

I can reproduce this issue on <https://privatebin.net>: Yes

### PR DESCRIPTION
**Pull request by elrido**
It gets excluded in the release archive, it's absence should not make any difference.

As per discussion in https://github.com/PrivateBin/PrivateBin/pull/1213/files/684924e9e57af8797edcc0bb48ebe3732d1a61c8#r1427426364

This PR closes #1208

### CODE REVIEW

File: tst/I18nTest.php [hunk 1]
```diff
@@ -167,6 +185,38 @@ public function testHtmlEntityEncoding()
...
+            ++$languageCount;
+            $this->assertTrue(copy($file, $path . DIRECTORY_SEPARATOR . $file->getBasename()));
+        }
+
+        I18nMock::resetPath($path);
+        $languagesDevelopment = I18nMock::getAvailableLanguages();
+        $this->assertEquals($languageCount, count($languagesDevelopment), 'all copied languages detected');
+        $this->assertTrue(in_array('en', $languagesDevelopment), 'English fallback present');
+
+        unlink($path . DIRECTORY_SEPARATOR . 'en.json');
```
Comment (rugk) [inline tst/I18nTest.php:209]: I would split it into two test ~~classes~~ functions (also to keep it readable and keep the mantra "one test per function").

But yeah…

**Review by rugk — APPROVED** [review]
