### PR TITLE
bootstrap5 dark mode toggle unset on dark browser preference

### LINKED ISSUE #1340: "Dark mode" toggle in Bootstrap 5 theme is not syncronised with prefers-color-scheme at start (when dark)
**Did you use the FAQ section?**
- [x] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

## Steps to reproduce

1. Use dark OS/browser design.
2. Visit PB instance with Bootstrap5 theme.
3. The night mode toggle is shown as disabled, although the night/dark mode is actually enabled.

### What happens

grafik

### What should happen

Either have some unspecific/third toggle state.
Or just enable the toggle if the dark mode is detected at loading time.

## Basic information

**Server address**:

**Server OS:** N/A

**Webserver:** N/A

**Browser:** Firefox 125

**PrivateBin version:** 1.7.3 / a0e42aae9e0935187c043acd5c16a4ec966aebdb

I can reproduce this issue on <https://privatebin.net>: Yes / No

### PR DESCRIPTION
**Pull request by elrido**
This PR fixes #1340

## Changes
* initialize including browser preferences, not just from local storage

### CODE REVIEW

File: js/dark-mode-switch.js [hunk 1]
```diff
@@ -68,9 +68,10 @@
     } else {
       delStoredPrettifyTheme()
     }
-    setTheme(getStoredPreferredTheme())
     const toggle = document.querySelector('#bd-theme')
-    toggle.checked = getStoredTheme() === 'dark'
+    const theme = getStoredPreferredTheme()
+    setTheme(theme)
```
Comment (rugk) [inline js/dark-mode-switch.js:73]: Hmm imho we should not save the setting unless the user actually triggers/clicks the toggle. This way, the system setting is always applied if the user does not touch the setting manually. So if the user just "wants system" then there is no need to save it and set a cookie or so.

**Review by rugk — CHANGES_REQUESTED** [review]

File: js/dark-mode-switch.js (hunk 1 above)
Comment (elrido) [reply js/dark-mode-switch.js:73]: `setTheme` only updates the current theme, while `setStoredTheme` will persist it in the local store (no cookies - they could leak to the server). See the event handler below that, where both get called, one to apply the new theme and the other to persist the selection.

**Review by rugk — APPROVED** [review]
