### PR TITLE
Numeric array key type errors

### LINKED ISSUE #1435: Fatal TypeError if paste ID all numeric
By chance, the paste ID PrivateBin generates can be all numeric, a 16 digit integer. Apparently, this throws a fatal TypeError at https://github.com/PrivateBin/PrivateBin/blob/b077fb77499674ae162f83a63498baeb60772795/lib/Request.php#L86

## Steps to reproduce

1. Generate pastes until the generated paste ID is all numeric, i.e. no [a-z].
2. Access (open) the paste.

### What happens

```
error GET /privatebin/ HTTP/2.0 mod_proxy_fcgi.c(911)
AH01071: Got error 'PHP message: PHP Fatal error: Uncaught TypeError:
strlen() expects parameter 1 to be string, int given in /web/privatebin/lib/Request.php:86
Stack trace:
#0 /web/privatebin/lib/Request.php(86): strlen()
#1 /web/privatebin/lib/Request.php(135): PrivateBin\\Request->getPasteId()
#2 /web/privatebin/lib/Controller.php(171): PrivateBin\\Request->__construct()
#3 /web/privatebin/lib/Controller.php(122): PrivateBin\\Controller->_init()
#4 /web/privatebin/index.php(17): PrivateBin\\Controller->__construct()
#5 {main}\n  thrown in /web/privatebin/lib/Request.php on line 86'
```

**Server OS:** Debian 11 Bullseye

**Webserver:** Apache 2.4.62 PHP 7.4 FPM

**PrivateBin version:** 1.7.4

I can reproduce this issue on <https://privatebin.net>: No (it would take very long) ;-)

### PR DESCRIPTION
**Pull request by elrido**
This PR fixes #1435

## Changes
* added a test to trigger the issue
* fixed the issue via explicit cast

## ToDo
There are two other areas I found that might have the same issue, but have not been able to trigger the issue from the outside - please review and share your thoughts:

* [x] In Configuration.php we iterate over the default configuration array - all keys happen to be strings, but we would get an issue if we ever introduced a number as a configuration key. Since these defaults are hardcoded, I don't know if we can trigger the potential breakage from a test: https://github.com/PrivateBin/PrivateBin/blob/d23bb748d45bb8cde8f3737b632d7ddd6a383e35/lib/Configuration.php#L147
* [x] In Database.php in the private _exec function, a flat array is used and we expect all keys to be int and never strings. All callers do so and therefore I again didn't find a way to call this from the unit tests: https://github.com/PrivateBin/PrivateBin/blob/d23bb748d45bb8cde8f3737b632d7ddd6a383e35/lib/Data/Database.php#L509-L510

So I think that at this time both of the above cases are un-problematic, but could be potential future foot-guns if used incorrectly?

### CODE REVIEW

**Comment by rugk** [comment]
Thanks a lot! This seems like the proper fix.

About your concerns:
* Configuration.php -> I agree here, nothing than strings can ever land. Especially, if it is really only the _keys_ of the configuration, they really are strings. We are very unlikely to introduce a numeric "key" like `123 = "this-option"`  or so … :upside_down_face: 
* database -> Here I don't have much insight into how that function is used and also it is internal-only.

So yeah hard to trigger from the outside, but IMHO, we could anyway do explicit casts, if you've already identified it as a problem. i mean casting strings explicitly to a string won't hurt, does it? I.e. let's fix the problem even if we have no unit test to prevent breakage.

File: tst/Bootstrap.php [hunk 1]
```diff
@@ -238,6 +238,17 @@ public static function getCommentJson()
...
 
+    /**
+     * Returns 16 random hexadecimal characters.
+     *
+     * @return string
+     */
+    public static function getRandomId()
+    {
+        // 8 binary bytes are 16 characters long in hex
+        return bin2hex(random_bytes(8));
```
Comment (rugk) [inline tst/Bootstrap.php:249]: FYI ah compared to the old method, this also seems you've modernized the code. :+1:

File: tst/RequestTest.php [hunk 2]
```diff
@@ -54,7 +42,25 @@ public function testView()
...
+        $request                   = new Request;
+        $this->assertFalse($request->isJsonApiCall(), 'is HTML call');
+        $this->assertEquals($id, $request->getParam('pasteid'));
+        $this->assertEquals('read', $request->getOperation());
+    }
+
+    /**
+     * paste IDs are 8 bytes hex encoded strings, if unlucky, this turns into
+     * a numeric string that PHP will cast to an int, for example in array keys
+     * @see https://www.php.net/manual/en/language.types.array.php
```
Comment (rugk) [inline tst/RequestTest.php:58]:
```suggestion
     * @see https://www.php.net/manual/en/language.types.array.php
     * @see https://github.com/PrivateBin/PrivateBin/issues/1435
```

(optional) Maybe we could link the issue, too, but any way is fine for me. It's explained, that's what matters…

**Review by rugk — CHANGES_REQUESTED** [review]
Only some nits, and as noted, maybe fix/cast the other things too? (Even if not covered by a specific unit test.)

File: lib/Request.php [hunk 3]
```diff
@@ -83,6 +83,7 @@ private function getPasteId()
     {
```
Comment (rugk) [inline lib/Request.php:83]: Ah and BTW (also to catch such errors), in the future, we could use type hints:
```php
private function getPasteId(): string
```

private function getPasteId()

Maybe let's create an issue to tackle this (as it is a general code-style/code improvement one may make)?

**Review by rugk — CHANGES_REQUESTED** [review]

File: tst/Bootstrap.php (hunk 1 above)
Comment (elrido) [reply tst/Bootstrap.php:249]: Discovered this code got duplicated, so better to use only one variant in multiple locations. Used the IMO more elegant version.

File: tst/RequestTest.php (hunk 2 above)
Comment (elrido) [reply tst/RequestTest.php:58]: The issue should already be linked in the git comment. IMO git comments is where you track the why a code got changed and comments in the code are for explaining the purpose and intent of a piece of code if it is non-obvious from just looking at the code.

**Comment by elrido** [comment]
I do not want to add the casts blindly if I can't create a test that trigger a problem.

For the config I tried to write one where I pass a config file that contains a numeric key, but that simply gets ignored by the loop, since we loop over known default keys.

In the database case it is a flat array (i.e. `array('first param', 'second param')`, so keys are expected to always be int (i.e. `0, 1` for the previous example). The only reason they would not be, is if someone added a call to exec_ passing an incorrect array (with string key) and then that PDO prepared statement call would fail because the bound params would not line up with the ? mark in the query. So it is unlikely to get added and remain undetected, unless we don't write a test for the new code path.

**Comment by rugk** [comment]
Okay then though our config should be safe. 

And okay, though I would have said a cast to the correct type does not hurt and an incorrect case would be detected as it breaks everything(?). So yeah…

File: lib/Request.php (hunk 3 above)
Comment (rugk) [reply lib/Request.php:83]: What do you think, could not you add the type dec. directly here? After we have now technically also ensured it is a string it would be a good starting point, and should be compatible?

Aka as indicated:
```php
private function getPasteId(): string
```

**Review by rugk — CHANGES_REQUESTED** [review]
Then fine, maybe only add the type hint…

File: lib/Request.php (hunk 3 above)
Comment (elrido) [reply lib/Request.php:83]: I don't like to be inconsistent - if we start doing these, we should do them all and in one go or we have an unreadable mess at our hands. I'm willing to start this experiment in the unit tests, but could not get myself to do it on just one method, so I did all methods on that class.

Result: One docblock was incorrect (return type was actually string not array, probably copy/pasted from prior function) and one return type I can't express with type hints: `void|string` - seems PHP is fine calling this string, even when in some cases no value is returned.

**Comment by elrido** [comment]
I also restated the database prepared statement argument binding to use a regular incremented position variable. That doesn't require using keys. Possibly more readable, too?

**Review by rugk — APPROVED** [review]

**Comment by rugk** [comment]
Thanks! LGTM.
