### PR TITLE
fix: do not encode source JSON translation string resulting in wrong display of special characters like '

### LINKED ISSUE #1712: [French translation issue] HTML entity character "&apos;" shows in text
## Steps to reproduce

1. Create a document, make it expire after the first read
2. Setup your browser to be in French
3. Read it, reload the page, it's now gone and the error text shows 

Image

### What happens
The formatting of the translated text is bogus.

### What should happen
The text ``&apos;`` should be ``'`` instead. 

## Basic information

**Server address**: Yours

**Server OS:** Yours

**Webserver:** Yours

**Browser:** Chrome 142

**PrivateBin version:** 2.0.3

I can reproduce this issue on <https://privatebin.net>: Yes

### PR DESCRIPTION
**Pull request by rugk**
Fixes #1712

Disclosure: Coded with help of Copilot. (description wrtten by me)

So this does indeed loosen the encoding a bit. However, IMHO, it was neither better before though. You could always bypass the encoding for `args{0]` when  you just include `<a` (or the other tag) somewhere or so.
This cleans up the code and makes it more understandable.

**One important notice:** This was (due to the exceptions before and afterwards) valid before and also now: Translators **could** (and can) if they have malicious intent, inject/do "XSS attacks". Thus, translations PRs (also from Crowdin) should be reviewed for wild HTML code inside translations. I suppose this is easy to fix, but anyway a valid risk.

But IMHO, we should teat the JSON files being part of our source code as a "trusted source". In the end, such an attak is basicaly just ends up being injecting malicious code. I hope such contributors would be detected.

References I explicitly checked again to not introduce an XSS here: https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html and the PHP doc for he HTML encoding.

I feel the safer way obviously would be encoding the _whole_ string _after_ translation (just like you should apply DOMPurify after everything), but as explained it was not done before and would break compatibility. Also, I looked through the sources and I see no risk described by doing it only for the "dangerous" "untrusted" inputs. Only here is a notice that `%s` shall not be used in some contexts, for example to define a tag: https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html#dangerous-contexts (obviously in such a case, attacks may be possible even with encoding; but again; this is nothing new)

The basic "problem" of it all is: We want HTML to be translated/be usable in our translation. If we'd get rid of that, we would get for sure rid of all such XSS attack possibilities. But that would be a bigger refactoring, so IMHO, this here is fine for a fix for the issue at hand.

Ah another point: I think the `is_int` check is harmless, but it's also kinda useless. Maybe it is some kind of obscure performance optimisation. (Yeah ints have nothing to encode as they have nothing that could be used for XSS, but they could also just be passed through that function.)

### CODE REVIEW

File: lib/I18n.php [hunk 1]
```diff
@@ -127,14 +127,13 @@ public static function translate($messageId, ...$args)
...
+        // to prevent XSS attacks when the message is inserted into HTML context
         $argsCount = count($args);
-        for ($i = 0; $i < $argsCount; ++$i) {
-            if ($i === 0) {
-                if (str_contains($args[0], '<a') || str_contains($args[0], '<kbd>')) {
-                    continue;
-                }
-            } elseif (is_int($args[$i])) {
+        for ($i = 1; $i < $argsCount; ++$i) {
+            if (is_int($args[$i])) {
```
Comment (elrido) [inline lib/I18n.php:136]: Note, the change will make it so that all strings are _always_ encoded, which means that messages containing links are broken.

Aside: The `is_int` skip is there so that int are not being converted to strings, which would make them fail in the sprintf as they would no longer fit the `%d` format.

File: tst/I18nTest.php [hunk 2]
```diff
@@ -182,7 +182,20 @@ public function testHtmlEntityEncoding()
         $result = htmlspecialchars($input, ENT_QUOTES | ENT_HTML5 | ENT_DISALLOWED, 'UTF-8', false);
         $this->assertEquals($result, I18n::encode($input), 'encodes HTML entities');
         $this->assertEquals('<a>some ' . $result . ' + 1</a>', I18n::_('<a>some %s + %d</a>', $input, 1), 'encodes parameters in translations');
-        $this->assertEquals($result . $result, I18n::_($input . '%s', $input), 'encodes message ID as well, when no link');
+        // Message ID should NOT be encoded (it comes from trusted source), only the parameter should be
```
Comment (elrido) [inline tst/I18nTest.php:186]: The comment is misleading, as the change above will instead encode the message ID under all circumstances.

File: tst/I18nTest.php [hunk 3]
```diff
@@ -182,7 +182,20 @@ public function testHtmlEntityEncoding()
...
+        $this->assertEquals($input . $result, I18n::_($input . '%s', $input), 'encodes only parameters, not message ID');
+    }
+
+    public function testFrenchApostropheInMessage()
+    {
+        $_SERVER['HTTP_ACCEPT_LANGUAGE'] = 'fr';
+        I18n::loadTranslations();
+        // The French translation should not have the apostrophe encoded
```
Comment (elrido) [inline tst/I18nTest.php]: The apostrophe can occur in any language, for example in the English "FOR YOUR EYES ONLY. Don't close this window, this message can't be displayed again." message ID. So I would clarify the comment - it isn't specific to French.

File: tst/I18nTest.php [hunk 4]
```diff
@@ -182,7 +182,20 @@ public function testHtmlEntityEncoding()
...
+        // Original: "Le document n'existe pas, a expiré, ou a été supprimé."
+        // Should NOT become: "Le document n&apos;existe pas, a expir&eacute;, ou a &eacute;t&eacute; supprim&eacute;."
+        $message = I18n::_('Document does not exist, has expired or has been deleted.');
+        $this->assertFalse(strpos($message, '&apos;') !== false, 'French apostrophe should not be encoded in translation message');
+        $this->assertTrue(strpos($message, "n'existe") !== false, 'French apostrophe should be present as literal character');
```
Comment (elrido) [inline tst/I18nTest.php:198]: Ok, good that the test was added, as the single quote is still encoded and the test catches this. IMHO the test is wrong, as we do want it to get encoded, normally.

File: lib/I18n.php (hunk 1 above)
Comment (rugk) [reply lib/I18n.php:136]: Ah int is fine.

> the change will make it so that all strings are always encoded, which means that messages containing links are broken.

Nope, see the i=1, the `0` is skipped, s links and normal HTML work fine.

File: tst/I18nTest.php (hunk 2 above)
Comment (rugk) [reply tst/I18nTest.php:186]: Again `i=1` not `i=0`, it's correct and works :)

File: tst/I18nTest.php (hunk 4 above)
Comment (rugk) [reply tst/I18nTest.php:198]: Nah the test catches the stupidness of Copilot indeed. ~~Just setting the language header does not change the translation.~~ (Edit: Ah, it's the traffic limiter as completly unrelated test, that is wild) I'll fix this. See the actual test output:
```
-'Merci d'attendre 4 secondes entre chaque publication.'
+'Please wait 4 seconds between each post.'
```

```
-'Votre adresse IP n'est pas autorisée à créer des documents.'
+'Your IP is not authorized to create documents.'
```

It#s EN vs FR that's the problem here :D

Comment (rugk) [reply tst/I18nTest.php:198]: Ah so the actual issue just was a state issue: We modify `HTTP_ACCEPT_LANGUAGE` in the I18n test but _never_ ever unset it. This time Copilot also wanted to unset it in `TrafficLimiterTest` but IMHO that is not good as the error lies in the other test and thus would be flaky/depend on the order the tests are executed.

Comment (rugk) [reply tst/I18nTest.php:198]: Okay no ah it is already unset, that is odd. Why does French persist… ah maybe the lang class needs reloading?

Comment (rugk) [reply tst/I18nTest.php:198]: Ah lol, no it persists the loaded messages uhm… :sweat_smile: 

We never tested the `I18n` class with a language other than English, so that's why the error was not apparent before. Quite funny… :sweat_smile: 

Proper stubbing the deps away would of course mean to remove/mock the I18n responses in the traffic limiter but yeah… I guess it's okay.

File: tst/I18nTest.php (hunk 3 above)
Comment (rugk) [reply tst/I18nTest.php]: Good point, yeah we _could_ also use English for testing etc., but I guess French is fine too. I clarified the comment though.

**Comment by rugk** [comment]
> But in some cases, mostly in the Controller class, when we return errors using the _return_message method, we may pass a translated message that ends up in a JSON response instead and we don't want those to get HTML encoded (our JSON serializer already handles JSON encoding).

Note this is fine as it is. JSON encoding should do JSON when it ends up in JSON. And HTML encoding should (and must!) do HTML when it ends up in HTML. Also _additionally_.
That's why I checked all that in my OP.

Note that when ' is HTML-encoded you cannot (and rather should not) decode it back. Either it works i the HTML insertion or it does not.

Granted, I did not check the whole execution path, but it is indeed sent from the server via JSON:
image

Granted, it depends on how that is treated then. If one inserts it with `.html` (or some other unsafe method) that is bad and encoding would be needed (also just not to accidentally destroy the HTML), so I looked a little bit into it. Here it seems to be extracted:
https://github.com/PrivateBin/PrivateBin/blob/14ffbc68e211e98a3852ddb28ff91d173487d078/js/privatebin.js#L1801

BTW, it seems _again_ to be passed through the Frontend translation, so yeah… also not needed. :sweat_smile: 
That one again then seems to do all the stuff of sanitizing it _again_ though it also says:
> messageID may contain HTML, but should be from a trusted source

So, I guess, we treat it the same in the backend now.

Ah and as the "translation" is no HTML, it is inserted as text (which is valid), and thus the rendering (double encoding) error occurs.

File: lib/I18n.php (hunk 1 above)
Comment (elrido) [reply lib/I18n.php:136]: Hang on - we do want the message ID escaped, unless it contains tags. We have messages that contain links, emphasis and key press sequences.

**Comment by elrido** [comment]
Just to share what ideas I had in mind on how this could be resolved:

### No Code Solution

For our purposes, the issue is mostly with apostrophes and quotes that might appear in the JSON API errors. So we could simply replace those apostrophes with a unicode character, such as U+2019 (`’`, the RIGHT SINGLE QUOTATION MARK) and double quotes with the language appropriate starting and ending quote marks (which is already the case in many translations).

The risk with this approach is simply that we miss some cases or that later new messages or changes in translations re-introduce the issue, which we could mitigate with a unit test. On the other hand, this is unlikely to have side effects or introduce risks of not encoding something we want encoded.

### Context Detection

As per earlier discussion, we would only need to disable encoding when in the JSON API context. We detect this in the Request class, here:

https://github.com/PrivateBin/PrivateBin/blob/9b3647141d61c8f3541073b38a5e14716e30cd50/lib/Request.php#L103-L104

We could extend the I18n class with a static call `disableEncoding` or such (and maybe a matching call to enable it again, for unit testing purposes), that toggles an on by default, private, static boolean inside it. Finally, we would wrap that loop in I18n into a conditional that hinges on that boolean:

https://github.com/PrivateBin/PrivateBin/blob/9b3647141d61c8f3541073b38a5e14716e30cd50/lib/I18n.php#L130-L141

The risk here is that we introduce fragility and the potential that messages that should get encoded are not, when we later change our logic. It is also less than stellar design that the Request becomes coupled to the I18n class. Maybe a better place to handle this would be in the Controller, right after parsing the request, to check for `$this->_request->isJsonApiCall()` before telling I18n to disable the encoding, around here-ish:
https://github.com/PrivateBin/PrivateBin/blob/9b3647141d61c8f3541073b38a5e14716e30cd50/lib/Controller.php#L184-L188

**Comment by rugk** [comment]
> No Code Solution

Possible, but typography people and French speakers would hate us for using the wrong character just because it looks the same. I trust the translators here to use the proper character.

> Context Detection

Yeah, possible, but IMHO this sounds overly complex. As said, the translation source is trusted by us anyway, so I see no real risk passing it through.

A proper solution, however, would be: 

## Remove backend localisation (where possible)

As in some issue people have stated it is anyway very strange that some stuff is localized in the backend and some in the Frontend. Especially the `TrafficLimiter` seems to be localized on the Frontend.

As I explained in my OP; actually the string _is already_ passed through the Frontend localisation anyway, so one would "just" need to figure out how to pass the variables (like the number of seconds one is blocked) to the Frontend and properly localize it there. Instead of on the backend. As it is a JSON request that should be possible.
Also, because it is localized on the Frontend, if every string is passed in there properly, it should also automatically be encoded/properly parsed in an XSS-safe way there, already.

---

Then encoding HTML entities only affects the strings passed into the PHP file on the backend. 
Architecturally, I guess one should split localisation and XSS-safe encoding, even in the backend. So you can localize how you want without encoding, but only _right before_ the string is inserted into the HTML the "template engine" (I know we have removed these and that's also fine, but usually template engines work like that) shall encode the characters.

File: lib/I18n.php (hunk 1 above)
Comment (rugk) [reply lib/I18n.php:136]: > We have messages that contain links, emphasis and key press sequences.

You mean `a`, ` kbd`  and `emph` tags? Yeah, why should we encode these and break them? The old code also did not encode these (except `emph`, but maybe that is only used in the Frontend). So, yes, this was the old logic:
> we do want the message ID escaped, unless it contains tags. 

My point is: It does not make sense to encode it at all, **if we have these exceptions**. 

That was my point in the OP:
>  However, IMHO, it was neither better before though. You could always bypass the encoding for args{0] when you just include <a (or the other tag) somewhere or so.

So if one where to exploit an XSS; which we try to prevent with encoding here, one could already do so: Just submit a malicious translation with an `a` tag inside it (_and_ your XSS payload).

Effectively exactly the "unless it contains tags" is a bypass/(intentional) "backdoor" of encoding/escaping that makes the whole escaping useless, IMHO.

**metaphor time:** It's otherwise like locking a door securely, but then storing the key to it near a stone directly in front of it. Sure, it's "more secure", but it's not the sense of security that makes sense, IMHO.
Now, if the result of this locking mechanism then have additionally bad side affects (as the bug being fixed here), we can remove the door.
If the system stays secure then, the door actually was not needed and just let to a playing area or so that is anyway better protected by other measures. (The metaphor ends here, because not everything that's a metaphor, works. But I hope you get my point. :upside_down_face:)

**Comment by elrido** [comment]
> A proper solution, however, would be:
> ## Remove backend localisation (where possible)

Agreed, that would be cleaner and lets us deal with the translations in a context aware manner.

In the backend, we could drop translation of most exceptions and JSON API error responses. Here are a few problematic cases and what we might do about them:

https://github.com/PrivateBin/PrivateBin/blob/6087cad88e6bc06538d6289b415a23eeb397596a/lib/Persistence/TrafficLimiter.php#L212-L215

This is translated on the backend, to inject the number into the string and have the translation pick the correct plural case. If we don't translate it, we need to change the back- and frontend to allow for passing an array of message ID and int, instead of only a string like now. Then the translation can occur on the frontend side.

Or we leave it translated and still translate all JSON API errors on the frontend - that should not lead to double encoding issues, as the string will be returned as is, if not found as a message ID and a notice is logged to the browser console, but the end user doesn't see this.

https://github.com/PrivateBin/PrivateBin/blob/6087cad88e6bc06538d6289b415a23eeb397596a/lib/Configuration.php#L153
https://github.com/PrivateBin/PrivateBin/blob/6087cad88e6bc06538d6289b415a23eeb397596a/lib/Configuration.php#L315

These are major errors that prevent the application to function correctly and that an admin needs to handle. So these are not end user errors that get displayed in a pretty fashion and turn up in the PHP error log instead. We could simply leave those untranslated or keep them translated, like now.

**Comment by rugk** [comment]
Okay, but I guess this is a new PR and starting it would be easier. Anyway, I stand by this PR and [already explained that here yet again](https://github.com/PrivateBin/PrivateBin/pull/1715#discussion_r2569955638) for a quick fix that would not require the refactoring (that likely would be useful, anyway).

I also saw https://github.com/PrivateBin/PrivateBin/pull/1718 which makes a lot of sense then.

Anyway I guess for further discussion on the refactoring I'd better create an issue: https://github.com/PrivateBin/PrivateBin/issues/1735
