### PR TITLE
fix: Bugs in the attachment functionality (#1824)

### LINKED ISSUE #1824: Bugs in the attachment functionality
**Did you use the FAQ section?**
- [X] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

**Bug 1: State corruption after "Remove attachment"**
Please try the following steps:
- Click New.
- Click Attach a File.
- Click Remove attachment (yes, I know there is no file yet, just click the button).

After this, any attempt to create a secret results in the following error: **Could not create document: Invalid data.**

The same effect occurs if you actually add an attachment and then remove it. Any subsequent attempt to create a secret (with or without a new attachment) fails until the page is refreshed.

**~~Bug 2: Attachment is dropped on "Paste" event~~**

- ~~Add an attachment to a new secret~~.
- ~~After the file is attached, perform a Paste (Cmd+V / Ctrl+V) into the Editor~~.
- ~~Create the secret~~.
- ~~Result: The secret is created silently, but the attachment is missing from the resulting data. If you open created link you'll see no attachment there (and there's really no attachment there)~~.

~~Note: If you perform any number of "Paste" actions before attaching the file, the secret is created correctly and the attachment is included as expected. It seems the "Paste" event in the Editor resets or corrupts the attachment state if it was already set.~~

P.S. **Bug 2** has already been fixed at https://github.com/PrivateBin/PrivateBin/pull/1737

## Basic information

**PrivateBin version:** 2.0.2, 2.0.3

I can reproduce this issue on <https://privatebin.net>: Yes

_Originally posted by @v6668468 in https://github.com/PrivateBin/PrivateBin/discussions/1813_

### PR DESCRIPTION
**Pull request by gittihub-jpg**
Fixes #1824

## Summary

This PR fixes attachment state handling after removing or pasting attachments.

## Changes

- Use actual attachment data to decide whether attachment data exists
- Avoid treating stale attachment UI state as real attachment data
- Avoid adding attachment names when no file list is available

## Testing

- PHPUnit passes: 266 tests, 6433 assertions
- Mocha fails locally on clean `master` as well with JS heap out of memory / jsverify shrink stack overflow, so this appears unrelated to this PR.

## Disclosure

I used an AI/LLM tool to help generate and review this change.

### CODE REVIEW

**Review by rugk — DISMISSED** [review]
LGTM from a first look, I just don't get why that change down the code iterating file names is doing.

Also can this be tested in a unit test? That would be awesome.

File: js/privatebin.js [hunk 1]
```diff
@@ -5227,7 +5230,10 @@ jQuery.PrivateBin = (function($) {
                 };
             if (attachmentsData.length) {
                 cipherMessage['attachment'] = attachmentsData;
-                cipherMessage['attachment_name'] = AttachmentViewer.getFiles().map((fileInfo => fileInfo.name));
+                const fileNames = AttachmentViewer.getFiles();
+                if (fileNames && Array.isArray(fileNames)) {
+                    cipherMessage['attachment_name'] = fileNames.map((fileInfo => fileInfo.name));
```
Comment (elrido) [inline js/privatebin.js]: The getFiles function returns a [FileList](https://developer.mozilla.org/en-US/docs/Web/API/FileList) object, which behaves a little like an array, but is not a true array. I assume, but have not tested, that Array.isArray will still recognize it as an array. The alternative is to use the [.length](https://developer.mozilla.org/en-US/docs/Web/API/FileList/length) property. Annoyingly we don't initialize the property that gets returned by getFiles, so we still need to check if it is not undefined.

So I suggest two changes:
- rename the const, so it is clearer that it is not a list of filenames but of files, which then helps explain why we need to use map and a lambda function to extract the filenames from the list of files
- just in case one of the browsers breaks some of their backwards compatibility around the FileList object  behaving array like while not being an array type, lets consider using the (more ugly) length check, as that property is defined in the interface

```suggestion
                const files = AttachmentViewer.getFiles();
                if (files && files.length > 0) {
                    cipherMessage['attachment_name'] = file.map((fileInfo => fileInfo.name));
```

**Review by elrido — COMMENTED** [review]
I suggest two minor tweaks, but don't want to block this PR if the Array.isArray does work in Firefox & Chrome and with their FileList type.

@Ribas160, as you had worked in the attachment logic more recently, could you also have a brief look at these changes and give us your feedback?

**Comment by Ribas160** [comment]
@gittihub-jpg 
First of all, thank you for taking time to contribute to the project

I just double-checked and found out that bug 2 `_Attachment is dropped on "Paste" event_` event had already been fixed earlier in the https://github.com/PrivateBin/PrivateBin/pull/1737. So, this bug should not have been added to this issue, I apologize for it.

But bug 1 `State corruption after "Remove attachment"` is still relevant and still exists after the changes that were made in this PR.

I want to pay attention that [Subresource Integrity (SRI)](https://www.w3.org/TR/SRI/) must be [regenerated](https://github.com/PrivateBin/PrivateBin/wiki/Development#subresource-integrity-for-javascript-resources) in case of javascript file change
https://github.com/PrivateBin/PrivateBin/blob/a34af1b62b804aa9c61b587f34455f46d2bc177d/lib/Configuration.php#L125

I also recommend attaching the URL to a test instance of PrivateBin into the PR description to make testing easier.

**Review by elrido — APPROVED** [review]
Thanks, I'll get it manually merged and update the SRI hash while doing so.

**Comment by gittihub-jpg** [comment]
Hi, thanks for the feedback foremost. so if i understand it right next time i need to addthe sri , but if as you said the patch does not fix the issue why is it being merged then?

**Comment by elrido** [comment]
Sorry, I misunderstood - It has not yet solved the state corruption upon remove?

**Comment by gittihub-jpg** [comment]
> @gittihub-jpg First of all, thank you for taking time to contribute to the project
> 
> I just double-checked and found out that bug 2 `_Attachment is dropped on "Paste" event_` event had already been fixed earlier in the #1737. So, this bug should not have been added to this issue, I apologize for it.
> 
> But bug 1 `State corruption after "Remove attachment"` is still relevant and still exists after the changes that were made in this PR.

as far as i understood this message the pr does not resolve the issue or not?

**Comment by rugk** [comment]
Do you mean "resolve" in a technical way or just that you want to (automatically) [let issues close](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) when a PR is merged? (The latter one was done so, the first one I suppose, it should also do? We really expect contributors to test the PRs they propose, after all…)

**Comment by gittihub-jpg** [comment]
Sorry, I meant the first one, since the other reviewing person stated otherwise, according to my testing it should be solved by this pr.

**Comment by Ribas160** [comment]
I've uploaded the current master version to my test instance and I can reproduce Bug 1 on it.
https://test.ribas160.ru/privatebin/
> **Bug 1: State corruption after "Remove attachment"**
> Please try the following steps:
> - Click New.
> - Click Attach a File.
> - Click Remove attachment (yes, I know there is no file yet, just click the button).

> After this, any attempt to create a secret results in the following error: **Could not create document: Invalid data.**

> The same effect occurs if you actually add an attachment and then remove it. Any subsequent attempt to create a secret (with or without a new attachment) fails until the page is refreshed.

Regarding the changes made in this PR, the root cause of this bug is not yet known, I am not sure if these changes are related to it and will not cause unexpected behavior in the future.
