### PR TITLE
fix regex check for short url in response

### LINKED ISSUE #1644: Short URL extraction fails when a valid URL exists in the response document from the proxy call
**Did you use the FAQ section?**
- [ ] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

## Steps to reproduce

1. Set frame-ancestors CSP directive to some valid URL (https://google.com) by updating the setting in `conf.php`
2. Create a paste and shorten the link

### What happens
The frame ancestor URL is extracted from the document and shown as the short URL

### What should happen
The short URL link must be extracted as expected

## Additional information

[](url)
## Basic information

**Server address**: https://bin.kastu.in

**Server OS:** Raspbian

**Webserver:**

**Browser:** Safari

**PrivateBin version:** 2.0.0

I can reproduce this issue on <https://privatebin.net>: No

### PR DESCRIPTION
**Pull request by karthikkasturi**
This PR fixes #1644

## Changes

* Updated the regex to have a lookahead and lookbehind match for conical brackets (html/xml) or quotes (json)

### CODE REVIEW

**Comment by karthikkasturi** [comment]
@elrido / @rugk  can you take a look at this

File: js/privatebin.js [hunk 1]
```diff
@@ -2151,7 +2151,7 @@ jQuery.PrivateBin = (function($) {
                 response = JSON.stringify(response);
             }
             if (typeof response === 'string' && response.length > 0) {
-                const shortUrlMatcher = /https?:\/\/[^\s"<]+/g; // JSON API will have URL in quotes, XML in tags
+                const shortUrlMatcher = /(?<=[>"])https?:\/\/[^\s"<]+(?=[<"])/g; // JSON API will have URL in quotes, XML in tags
```
Comment (elrido) [inline js/privatebin.js]: Unfortunately this RegEx fails in our IDN URL test. Would adding the semicolon as a terminator address the issue?
```suggestion
                const shortUrlMatcher = /https?:\/\/[^\s"<;]+/g; // JSON API will have URL in quotes, XML in tags, CSP may contain URLs separated by semi colon
```

Or we could remove that CSP-meta-tag from the shortener proxy template - it's not something the user opens in a browser tab and is only there in case a misconfigured webserver strips the CSP header from the response.

Comment (karthikkasturi) [reply js/privatebin.js]: I believe the better option here is to remove the tag from the template altogether, because adding the semi-colon in the regex at that point does not work as per my checks on regex101. And even if it did work, it would be a problem if the semicolon is not present in the csp string (a valid case when `frame-ancestors` is the last item in the csp list)
image

Comment (rugk) [reply js/privatebin.js]: BTW I personally also suggest adding links to regex101 fir regex things.
