### PR TITLE
Shortener URL validation improvement

### LINKED ISSUE #1224: URL shortener support excludes IDNs
**Did you use the FAQ section?**
- [x] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

When using a URL shortener hosted on an internationalized domain name (IDN), PrivateBin treats valid responses from the shortener as incorrect. As the root cause, I've located a regex in client-side JavaScript that assumes the URL is ASCII only.

https://datatracker.ietf.org/doc/html/rfc2181#page-13
https://datatracker.ietf.org/doc/html/rfc3490

Submitting this as a bug rather than a pull request because I imagine the maintainers would prefer to decide philosophically how to handle URL parsing rather than being dictated to by a stranger. :)

## Steps to reproduce

1. Host a URL shortener at an internationalized domain and generate an API key for PrivateBin
2. Configure PrivateBin's `urlshortener` option with the API key as documented
3. Configure CORS to allow the shortener service
4. Submit a paste in PrivateBin
5. Click the "Shorten URL" button

### What happens

A message appears at the top of the page saying, "Cannot parse response from URL shortener." Looking at the developer console in the browser, the AJAX request succeeded with a 200 response, and the response body contained a valid URL.

### What should happen

The shortened URL in the successful response body should display. There is a regex in `privatebin.js` that limits the domain portion of a URL to `[-a-zA-Z0-9@:%._\+~#=]{1,256}`. If I edit this segment of the regex in the Chromium console to `.{1,256}`, the shortened URL does display properly.

Incidentally, the same regex limits the TLD portion of the URL to six characters. While this isn't impacting me directly, there are many TLDs longer than six characters: https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains

One approach to a solution could be to modify the regex to include more valid domains. Another could be to require the URL shortener to represent its output in Punycode and, in JavaScript, decode the URL to its proper IDN form before displaying. Perhaps encode to Punycode, then run through a regex to validate, then decode again. Up to you how to tackle--I'm just a user. :)

## Additional information

Error message:

image

Inline-edited regex (right) with resulting successful flow (left, domain obfuscated):

image

## Basic information

**Server OS:** Alpine Linux (deployed through PrivateBin's official Helm chart, which uses the privatebin/nginx-fpm-alpine Docker image)

**Webserver:** nginx (deployed through PrivateBin's official Helm chart, which uses the privatebin/nginx-fpm-alpine Docker image)

**Browser:** Chromium 120 (also reproduced in Firefox 121)

**PrivateBin version:** 1.6.2

I can reproduce this issue on <https://privatebin.net>: No (for reasons that seem entirely logical to me :) )

### PR DESCRIPTION
**Pull request by elrido**
This PR (attempts to) fixes #1224

## Changes
* relax URL finding regex
* but add a filter based on built-in URL class, relying on browsers to validate potential URLs

## ToDo
* [x] would need some larger refactoring to allow unit testing this function
* [x] add unit tests
* [ ] get this validated by the reporter of the issue

### CODE REVIEW

**Review by rugk — APPROVED** [review]
I like the simplicity of the solution.

Just FYI it seems the API is quite new: https://caniuse.com/mdn-api_url_canparse_static

**Comment by rugk** [comment]
Oh sorry accidentally pressed the "wip done" button.

**Comment by elrido** [comment]
> Just FYI it seems the API is quite new: https://caniuse.com/mdn-api_url_canparse_static

Right, not supported in 115esr here on my Debian. Oh well, lets fall back to try-catch, then.

File: js/privatebin.js [hunk 1]
```diff
@@ -2123,6 +2101,42 @@ jQuery.PrivateBin = (function($, RawDeflate) {
...
+        me.extractUrl = function(response)
+        {
+            if (typeof response === 'object') {
+                response = JSON.stringify(response);
+            }
+            if (typeof response === 'string' && response.length > 0) {
+                const shortUrlMatcher = /https?:\/\/[^\s]+/g;
+                const shortUrl = (response.match(shortUrlMatcher) || []).filter(function(a) {
+                    return URL.canParse(a);
+                }).sort(function(a, b) {
```
Comment (rugk) [inline js/privatebin.js:2127]: Why that sorting? Want to extract the shortest or longest URL hmm? This is kinda prone to fail… (e.g. what happens if the terms linked at https://somedomain.com/terms are shorter than https://somedomain.com/aHTZg61?) Maybe just use the first?

Or this would need to be configurable in the backend, the admin likely knows whether the first or shortest URL is the correct one…

**Review by rugk — CHANGES_REQUESTED** [review]

File: js/privatebin.js [hunk 2]
```diff
@@ -2119,7 +2119,11 @@ jQuery.PrivateBin = (function($, RawDeflate) {
             if (typeof response === 'string' && response.length > 0) {
                 const shortUrlMatcher = /https?:\/\/[^\s]+/g;
                 const shortUrl = (response.match(shortUrlMatcher) || []).filter(function(a) {
-                    return URL.canParse(a);
+                    try {
+                        return !!new URL(a);
```
Comment (rugk) [inline js/privatebin.js:2123]: > This is a fast and easy alternative to constructing a URL within a [try...catch](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch) block.

https://developer.mozilla.org/en-US/docs/Web/API/URL/canParse_static

Apparently that canParse has a performance benefit, so maybe still use it if possible?
We could include a polyfill so our own code does not need to be uglified just because old browsers do not support it yet? https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/web.url.can-parse.js

Or maybe at least keep a todo somewhere to change it in the future?

**Review by rugk — CHANGES_REQUESTED** [review]

**Review by rugk — CHANGES_REQUESTED** [review]

File: js/privatebin.js (hunk 1 above)
Comment (elrido) [reply js/privatebin.js:2127]: My guess is as good as yours, as I didn't write the code. I assumed it would order the longest first, since it subtracts the lengths, making the sign negative if b is longer than a, so b would be less than a = ranked higher. So it finds the longest URL in the block of text, HTML or JSON given?

File: js/privatebin.js (hunk 2 above)
Comment (elrido) [reply js/privatebin.js]: Yes, thats literally the polyfill used. :-) I added the check to retain canParse use if present.

File: js/privatebin.js (hunk 1 above)
Comment (rugk) [reply js/privatebin.js:2131]: But does that make sense given it should create a short link?

Again a reason to write it more descriptive, so having a function "getLongest" or "getShortest" URL?

File: js/privatebin.js (hunk 2 above)
Comment (rugk) [reply js/privatebin.js]: Well you replaced it, you did not use the polyfill. As stated it apparently has a performance benefit so yeah…

Comment (rugk) [reply js/privatebin.js]: Ah okay fixed.

File: js/privatebin.js (hunk 1 above)
Comment (elrido) [reply js/privatebin.js:2131]: I really can't answer that without having more context. We need examples of what these API responses look like. Thats why I had asked for such samples to get shared in the ticket.

Lacking that, the test that I've added only generates a single random URL per test iteration and assumes the API response consists of a single URL. We got told that some APIs return some JSON message and others HTML, but I've not done much research - I really don't like the URL shortener feature, but as it is popular I'm willing to help support it. This logic was contributed by a kind member of the community and I don't want to remove it without knowing what the impact of doing so will be. I have to assume that the current logic works for people (except for the IDN bit we are trying to fix here) and was eager to do this small change because it lets us simplify one of those inscrutable regexes.

PS: Here is some doc I found from Yourls, which includes a sample JSON and XML response: https://yourls.org/readme.html#API;apireturn - in that example the longurl happens to be shorter than the shorturl, but I can see that with the above logic it will tend to find the paste URL itself, instead.

Comment (rugk) [reply js/privatebin.js:2131]: Yeah ideally we should have had examples or a unit test when this was initially implemented, so we cannot break the behaviour for some setting.

But too late now I suppose, so feel free to merge.

**Review by rugk — APPROVED** [review]

File: js/privatebin.js (hunk 1 above)
Comment (rugk) [reply js/privatebin.js:2131]: /cc @Haocen who apparently implemented this in https://github.com/PrivateBin/PrivateBin/commit/cd5ede5670985e6985d01d6cbce87b85f4c130da / https://github.com/PrivateBin/PrivateBin/pull/480

If you read this, some questions we have:
* Why is the longest URL filtered out?
* Can we have example responses that it works with?
* With which URL shorters has this been tested?

Comment (rugk) [reply js/privatebin.js:2131]: Maybe it also was a bug and actually it was intended to get the short URL?
Because in PrivateBin the hash is sooo long that the long URL would almost always be the wrong one (unless you have a _huge_ domain name).
The question just arises, why was this issue never noticed?

Some ideas I have about this:
* Maybe include the YOURLS examples you have found in the tests. Or at least the structure (like JSON and ML but with a PB URL). This way we have a realistic test/use case. (It does not need to be randomized IMHO. We have a fixed target API in case of YOURLS, which we often mention in the project docs as a suggestion, so it's a good reference IMHO).
  Reason: In the future, we could implement a simple parsing trying some well-known URL shorters (like `shortURL in response`, if it is JSON etc.), maybe implemented as [a strategy pattern](https://en.wikipedia.org/wiki/Strategy_pattern), but IMHO this is future stuff, although it could be implemented right now, too. But I would like to keep it simple for now.)
* Maybe in the list of URLs retreived we could filter out our own URL i.e. the long URL? I.e. just filter it out `document.URL`?
   Reason: Then sorting does not matter that much and this is clearly the wrong URL.
   Note: I also thought just filtering out the current domain, but that is prone to fail, if someone chooses to host the URL shortener on the same domain as the PrivateBin instance itself.
* Otherwise I still personally feel like choosing the longest URL is a bug, but of course I cannot be certain.

Comment (Plausible0Bug) [reply js/privatebin.js:2131]: Hi, 👋
It's been a while.
The original logic is to find all URLs in the response and get the shortest one.
In a few URL shortener I tested, including TinyURL and YOURLS, they tend to include the original URL as well as the shortened URL.

Given that background, the logic for parsing an unknown structure response from URL shortener would be:
- extract Any URL like strings from the response.
- sort them from shortest to longest order.
- take the shortest one from all URLs.

It was working as expected when I implemented it and you can refer to how `sort` function works here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

Comment (elrido) [reply js/privatebin.js:2131]: Ok, let me merge this as is, but then I'll create another branch with additional tests based on the samples found for Yourls. Then we'll at least learn about the behaviour with short- and longurl parameters and can explore if this can be a bug or not and fix it if found necessary.
