### PR TITLE
Use blob URI for saving attachments (#432)

### LINKED ISSUE #432: Chromium fails to download attachment if bigger than 2MB
## Steps to reproduce

1. Attach any file over 1.5MB (apparently - https://stackoverflow.com/questions/47353040/)
2. Try to download in Chromium (or Chrome)

### What happens

File fails to download with "Failed - Network error"

### What should happen

File downloads successfully as it does in Firefox.

## Additional information

I uploaded a 4MB image file and some builds with confidential information on them and users using Chromium as their Browser failed to download the attachments.

Downloading with Chrome works fine apparently when the files are below 1.5MB because of the way PrivateBin initiates the download.

I've tried the following:

https://stackoverflow.com/a/3916267

Possible solutions:

https://stackoverflow.com/questions/38781968/
https://stackoverflow.com/questions/50458942/
https://stackoverflow.com/questions/53560122/

## Basic information

Debian 9.5

nginx 1.14.0

Chromium (Version 74.0.3729.131)

1.21

I can reproduce this issue on <https://privatebin.net>: No, because it has no file attaching capability

### PR DESCRIPTION
**Pull request by r4sas**
Leave IE with `msSaveBlob`, because it not support `blob:` uri too (at least my IE11 doesn't set uri to it).
Tested on Chromium 67 (x64, Win 8.1).
Fixes #432.

In addition, `$attachmentPreview` also can be used with blob, but it requires creating element with blob link as source.

### CODE REVIEW

File: js/privatebin.js [hunk 1]
```diff
@@ -2818,6 +2820,73 @@ jQuery.PrivateBin = (function($, RawDeflate) {
...
+                            .attr('controls', 'true')
+                            .attr('autoplay', 'true')
+
+                            .append($(document.createElement('source'))
+                            .attr('type', mimeType)
+                            .attr('src', blobUrl))
+                    );
+                } else if (mimeType.match(/\/pdf/i)) {
+                    // PDFs are only displayed if the filesize is smaller than about 1MB (after base64 encoding).
+                    // Bigger filesizes currently cause crashes in various browsers.
```
Comment (r4sas) [inline js/privatebin.js]: That need check with blob data.

**Comment by elrido** [comment]
I'll test and look into the InvalidCharacterError thrown in the unit tests on the weekend.

**Comment by r4sas** [comment]
>Counterexample: "image/png"; ["c"]; ""; ""; "";

It creates base64 encoded "file" with only one symbol,  and then in `atob` we got error because can't decode it.

**Comment by elrido** [comment]
Hi again, thank you for your work, I just merged it in.

A few findings:
- Changed the unit test to do the btoa of a random string instead and added a mock function for `window.URL.createObjectURL` which isn't emulated by jsDOM at this time.
- I had to change the CSP to allow for blob-URLs instead of data ones. Hindsight is 20/20.
- Did test quite a few cases of different media in Firefox and Chrome, found that:
  - Neither has an issue with larger files (tested up to the 10 MiB limit on my test instance) anymore, so I removed the already commented out bit reg. Firefox crashing on PDFs larger then 1.5 MiBs. Maybe was the case with data-URLs, but not with blobs.
  - Chrome doesn't show the PDF preview, because "Failed to load 'blob:[...]/d36704a3-2283-438a-b0ae-030a4046be7e' as a plugin, because the frame into which the plugin is loading is sandboxed.", but the download link works fine.
  - I generally had the impression that en-/decryption in Chrome was about twice as long then in Firefox. Chrome also hogged all four CPUs during this for several seconds, while Firefox seemed to just ramp up a quick CPU spike for about a second. This was mostly noticeable when creating/viewing files with 5 - 10 MiBs. Maybe we do need to add that loading bar in the next release after all, to better understand which part is slow in Chrome. My bets are on the zlib WASM module, Chrome might sandbox this "better" then FF.
